version: "3.9"

services:
    django:
        environment:
            - DJANGO_ENV=production
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        command: sh -c "python manage.py collectstatic &&
            python manage.py runserver 0.0.0.0:8000"
