version: "3.9"

services:
    django:
        environment:
            - DJANGO_ENV=development
    react:
        command: npm start
        environment:
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
