"""Module generated by django to create the booksearch app"""
from django.apps import AppConfig


class BooksearchConfig(AppConfig):
    """
    Configuration for the booksearch app
    """

    default_auto_field = "django.db.models.BigAutoField"
    name = "src.booksearch"
