FROM solr:8.10

ADD merge /data/books

ADD models /models

COPY books_schema.json /data/books_schema.json

COPY config.xml config.xml

COPY synonyms.txt /data/synonyms.txt

COPY startup.sh /scripts/startup.sh

ENTRYPOINT ["/scripts/startup.sh"]
